Repository ucsb-cs156-f22/f22-6pm-happycows, pull requests merged in 2022-12, with the labels that each got.

#45 ic - Add cow death controller
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CowDeathController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/CowDeath.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CowDeathRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CowDeathControllerTests.java
Labels: 20, f22-6pm-4, STAFF: ready for review

#60 Add carryingCapacity to frontend
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
  src/.DS_Store
Labels: 10, f22-6pm-3

#71 Jv update cow health job
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobFactory.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
Labels: 20, f22-6pm-3
