Repository ucsb-cs156-f22/f22-6pm-happycows, pull requests merged in 2022-11, with the labels that each got.

#2 ic - Add function in jobs controller for milking the cows
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
Labels: 5, f22-6pm-4

#16 vs - added placeholder jobs for update cow health and instructor report + tests
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/InstructorReportJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/InstructorReportJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
Labels: 10, f22-6pm-4

#11 now it shows pacific time as required
  frontend/src/fixtures/jobsFixtures.js
  src/main/java/edu/ucsb/cs156/happiercows/HappierCowsApplication.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/jobs/Job.java
Labels: 10, f22-6pm-3

#7 Add sourceRepo to SystemInfo object
  src/main/java/edu/ucsb/cs156/happiercows/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImpl.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/happiercows/controllers/SystemInfoControllerTests.java
Labels: 10, f22-6pm-3

#29 JC - Add Stryker CI/CD Test and other frontend/backend tests only when frontend/backend changes
  .github/workflows/10-backend-unit.yml
  .github/workflows/12-backend-jacoco.yml
  .github/workflows/14-backend-pitest.yml
  .github/workflows/30-frontend-tests.yml
  .github/workflows/32-frontend-coverage.yml
  .github/workflows/34-frontend-mutation-testing.yml
  .github/workflows/36-frontend-eslint.yml
Labels: f22-6pm-3

#8 jz - added component to submit the MilktheCowsJob
  frontend/src/main/components/Jobs/MilkCowsJobForm.js
  frontend/src/main/pages/AdminJobsPage.js
Labels: f22-6pm-4

#43 ic - add cow death entity and repository
  src/main/java/edu/ucsb/cs156/happiercows/entities/CowDeath.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CowDeathRepository.java
Labels: 10, f22-6pm-4, STAFF: ready for review

#18 jv - update footer to include systemInfo.soureRepo value
  frontend/src/fixtures/systemInfoFixtures.js
  frontend/src/main/components/Nav/Footer.js
  frontend/src/main/layouts/BasicLayout/BasicLayout.js
  frontend/src/stories/components/Nav/Footer.stories.js
  frontend/src/tests/components/Nav/Footer.test.js
Labels: 10, f22-6pm-3

#32 jv - update join a commons list
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/pages/HomePage.test.js
Labels: f22-6pm-3, STAFF: ready for review

#51 pc - pay down testing tech debt in MilkCows Job
  frontend/src/main/components/Jobs/MilkCowsJobForm.js
  frontend/src/main/pages/AdminJobsPage.js
  frontend/src/tests/components/Nav/Footer.test.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: Staff PR

#40 jz - Remove "This game will end on"
  frontend/src/main/components/Commons/CommonsOverview.js
Labels: 5, f22-6pm-4

#46 SC - Implemented Carrying Capacity field to Commons
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/fixtures/userCommonsFixtures.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: 10, f22-6pm-3

#47 SY - Change visibility on Leaderboard page so table is readable
  frontend/src/main/pages/LeaderboardPage.js
Labels: f22-6pm-4

#62 vs - added avgCowHealth to userCommons
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ProfitsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: f22-6pm-4

#34 Taeho-fixed cow bought/sold bug
  .DS_Store
  frontend/src/main/pages/PlayPage.js
  issues/.DS_Store
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/errors/NotEnoughCowException.java
  src/main/java/edu/ucsb/cs156/happiercows/errors/NotEnoughMoneyException.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: 10, f22-6pm-3

#67 Irene cow death controller pc2
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CowDeathController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CowDeathControllerTests.java
Labels: Staff PR

#65 pc - createdAt should not be input, but instead automatically populated
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CowDeathController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CowDeathControllerTests.java
Labels: Staff PR

#57 SC - Carrying Capacity column added to Admin's List Commons page
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
Labels: 10, f22-6pm-3
